server:
  port: 8081

spring:
  application:
    name: blog-be
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: D:\MyProject\imageDir
